### ISSUE TITLE
Add custom Search Parameters added by API team to GitHub

### ISSUE THREAD

**Issue by arunsundar-m** [jfabrizio329/signal-mso-fhir-profiles#155]
There are certain custom search parameters added by the API team. DM team should be adding this as part of our FHIR packages so that this will be taken care of during the deployment of our package.

- patient city
- ssn
- providerclientid

**Comment by Gokulsignal** [comment]
API team created the Custom Search Parameters and tested on the DEV environment. After the deployment is successful in DEV, they have deployed on the QA environment as well. 

It's informed that, going forward API team will let the DM team know regarding the FHIR changes, so that we can add this to our package.

This also will be discussed coming week with the team members.
